# Site
name: 'TwoSatoshis'
description: 'My Two Satoshis on the Block.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'twosatoshis'
email: 'satoshistwo@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           twosatoshis
      site:           www.twosatoshis.me
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, Here's my two satoshis on the block. I'll be logging my finds, my rambles, contributions, my notes and thoughts-- my two satoshis on the block."
      email:          satoshistwo@gmail.com
      twitter:        https://twitter.com/two_satoshis

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
